Sm03lebr00t/feature/suggest side
MathiasKandelborg/Twitch-Discord-Bot pull request #2
Opened 2020-11-22 19:15 UTC by Sm03leBr00t

## What does this do?

this adds the `suggest side` redemption, which allows viewers to suggest a side project. The suggestion will be added to a specified file.

## What can be improved?

- [ ] retrieve file path from somewhere else
- [ ] add propper logging

2020-11-22 19:16 UTC, Sm03leBr00t commented
✅ PR no conflicts, code looks ok, merging...

2020-11-22 22:51 UTC, MathiasKandelborg requested changes
🥰

2020-11-22 22:51 UTC, MathiasKandelborg commented on src/channel_points_redemption.rs
> +                let mut tempdir = temp_dir();
temp_dir what 🥰

2020-11-22 22:53 UTC, MathiasKandelborg commented on src/twitch.rs
> +        self.settings = settings;
We wanna have it it the else :D

2020-11-22 22:55 UTC, Sm03leBr00t commented on src/channel_points_redemption.rs
> +                let mut tempdir = temp_dir();
will create a temporary PathBuf

2020-11-22 22:55 UTC, Sm03leBr00t commented on src/twitch.rs
> +        self.settings = settings;
maybe maybe not I can change that

2020-11-23 22:29 UTC, MathiasKandelborg approved these changes

2020-11-23 22:29 UTC, merged